# Generated by Django 6.0 on 2026-05-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
