# Generated by Django 6.0 on 2026-05-03 06:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_cloudinary_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cloudinary_public_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
